site_name: CEQUEAU Documentation
site_url: https://erinconv.github.io/CEQUEAU/ # <-- UPDATE If USERNAME/REPO differs
repo_url: https://github.com/erinconv/CEQUEAU # <-- UPDATE If USERNAME/REPO differs
repo_name: CEQUEAU Model             # <-- UPDATE If USERNAME/REPO differs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en # Or 'fr' if preferred
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - mkdoxy:
      projects:
        cequeau_project:
          src-dirs: src
          full-doc: False
          doxy-cfg-file: Doxyfile
          doxy-cfg:
            DOXYFILE_ENCODING: UTF-8
            INPUT_ENCODING: UTF-8
            XML_PROGRAMLISTING: NO  # Disable code snippets in XML to reduce potential encoding problems
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - footnotes
  # Enable MathJax
  - pymdownx.arithmatex:
      generic: true

# Navigation
nav:
  - CEQUEAU Model:
    - index.md
    - User Guide: guide.md
    - Inputs and Outputs: inputs_outputs.md
    - Octave Notes: octave_notes.md
  - Development Guide: development.md
  # - API Reference: 
  #   - Overview: api.md
  #   - Core Classes:
  #     - BassinVersant: api/bassin_versant.md
  #     - CarreauEntier: api/carreau_entier.md
  #     - CarreauPartiel: api/carreau_partiel.md
  #     - Simulation: api/simulation.md
#   - ... etc 

# Add MathJax Javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 