site_name: CEQUEAU Documentation
site_description: Documentation for the CEQUEAU hydrological model
site_author: CEQUEAU Team
site_url: https://erinconv.github.io/CEQUEAU/
repo_url: https://github.com/erinconv/CEQUEAU
repo_name: CEQUEAU Model

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.tabs
    - content.code.copy

plugins:
  - mkdoxy:
      projects:
        CEQUEAU:
          src-dirs: src
          full-doc: True
          doxy-dir: doxygen/xml
          auto-doxy: True
          generate-autolisting: True  # Generates listing pages automatically
          doxy-cfg:
            DOXYFILE_ENCODING: UTF-8
            INPUT_ENCODING: UTF-8
            XML_PROGRAMLISTING: NO
            MARKDOWN_SUPPORT: YES
            AUTOLINK_SUPPORT: YES
            BUILTIN_STL_SUPPORT: YES
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

# Navigation
nav:
  - Home: 
    - 'index.md'
    - 'license.md'
    - 'contributing.md'
    - 'code_of_conduct.md'
  - API Documentation:
    - 'api.md'
    - 'api/simulation.md'
    - 'api/bassin_versant.md'
    - 'api/carreau_entier.md'
    - 'api/carreau_partiel.md'
  - API Reference:
    - 'CEQUEAU/annotated.md'

# Add MathJax Javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js 

# Ensure proper encoding of extra files
