name: Deploy Documentation

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs-deploy.yml'
  
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-mkdoxy
          
      - name: Check if mkdocs.yml exists
        id: check_files
        run: |
          if [ -f mkdocs.yml ]; then
            echo "mkdocs_exists=true" >> $GITHUB_OUTPUT
          else
            echo "mkdocs_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Setup mkdocs configuration if not exists
        if: steps.check_files.outputs.mkdocs_exists != 'true'
        run: |
          echo "Creating default mkdocs.yml configuration"
          cat > mkdocs.yml << EOF
          site_name: CEQUEAU Documentation
          theme:
            name: material
            palette:
              primary: indigo
              accent: indigo
          markdown_extensions:
            - pymdownx.highlight:
                anchor_linenums: true
            - pymdownx.superfences
            - pymdownx.inlinehilite
            - admonition
            - pymdownx.details
          nav:
            - Home: 'index.md'
            - API Reference:
              - Simulation: 'api/simulation.md'
              - BassinVersant: 'api/bassin_versant.md'
              - CarreauEntier: 'api/carreau_entier.md'
              - CarreauPartiel: 'api/carreau_partiel.md'
          EOF
          
      - name: Create index page if not exists
        run: |
          mkdir -p docs
          if [ ! -f docs/index.md ]; then
            echo "Creating default index.md"
            cat > docs/index.md << EOF
            # CEQUEAU Documentation
            
            Welcome to the official documentation for the CEQUEAU hydrological model.
            
            ## Available Documentation
            
            - [API Reference](api/)
              - [Simulation Class](api/simulation.md)
              - [BassinVersant Class](api/bassin_versant.md)
              - [CarreauEntier Class](api/carreau_entier.md)
              - [CarreauPartiel Class](api/carreau_partiel.md)
            EOF
          fi
          
      - name: Build documentation
        run: mkdocs build --site-dir ./_site
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 