name: Deploy Documentation

on:
  push:
    branches:
      - main  # Set this to your default branch
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements-docs.txt'
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-docs.txt
      
      - name: Generate Doxygen XML
        run: doxygen Doxyfile
      
      - name: Deploy documentation
        run: mkdocs gh-deploy --force
